[package]
name = "mega"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deno_core = "0.167.0"
serde = "1.0"
tokio = { version = "1.24.2", features = ["full"] }
toml = "0.6.0"
